// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package main

import (
	"time"
)

// Defines values for TodoStatus.
const (
	TodoStatusDone TodoStatus = "done"

	TodoStatusOnHold TodoStatus = "on_hold"

	TodoStatusWorking TodoStatus = "working"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Todo defines model for Todo.
type Todo struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          *int32     `json:"id,omitempty"`
	Status      TodoStatus `json:"status"`
	Task        string     `json:"task"`
	User        string     `json:"user"`
}

// TodoStatus defines model for Todo.Status.
type TodoStatus string

// GetTodosParams defines parameters for GetTodos.
type GetTodosParams struct {

	// ID of the user
	User string `json:"user"`

	// filter todo's by status
	Status *GetTodosParamsStatus `json:"status,omitempty"`
}

// GetTodosParamsStatus defines parameters for GetTodos.
type GetTodosParamsStatus string

// CreateTodoJSONBody defines parameters for CreateTodo.
type CreateTodoJSONBody Todo

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody CreateTodoJSONBody
